defaultIndent: "  "

modifyLineBreaks:
  preserveBlankLines: 1
  condenseMultipleBlankLinesInto: 1
  textWrapOptions:
    columns: 100
    perCodeBlockBasis: 1
    all: 1
  removeParagraphLineBreaks:
    all: 1
    beforeTextWrap: 1
